name: test

on:
  pull_request:

jobs:
  upgrade:
    name: "Upgrade test"
    runs-on: macos-12
    timeout-minutes: 120
    strategy:
      matrix:
        oldver: ["v0.23.1"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    # - name: Cache image used by ${{ matrix.oldver }}/examples/ubuntu-lts.yaml
    #   uses: ./.github/actions/setup_cache_for_template
    #   with:
    #    template: https://raw.githubusercontent.com/lima-vm/lima/${{ matrix.oldver }}/examples/ubuntu-lts.yaml
    - name: Install test dependencies
      run: |
        set -eux -o pipefail
        brew install bash coreutils
        curl -L -o qemu-8.2.1.monterey.bottle.tar.gz -H "Authorization: Bearer QQ==" \
            https://ghcr.io/v2/homebrew/core/qemu/blobs/sha256:41c77f6bac3e8c1664c665fbe2b19b19ee9da57f8e1ad6697348286710cc3575
        tar tvfz ./qemu-8.2.1.monterey.bottle.tar.gz
        brew install --ignore-dependencies ./qemu-8.2.1.monterey.bottle.tar.gz
    - name: Manual install
      run: |
        set -eux -o pipefail
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/v0.23.1/lima-0.23.1-Darwin-x86_64.tar.gz" | tar Cxzvm /usr/local
        env
        qemu-system-x86_64 --version
        limactl --version
        limactl start --tty=false --log-level=debug
        limactl shell default cat /etc/os-release
    - if: always()
      uses: ./.github/actions/upload_failure_logs_if_exists
