name: test

on:
  pull_request:

jobs:
  upgrade:
    name: "Upgrade test"
    runs-on: macos-12
    timeout-minutes: 120
    strategy:
      matrix:
        oldver: ["v0.23.1"]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: 1.23.x
    # - name: Cache image used by ${{ matrix.oldver }}/examples/ubuntu-lts.yaml
    #   uses: ./.github/actions/setup_cache_for_template
    #   with:
    #    template: https://raw.githubusercontent.com/lima-vm/lima/${{ matrix.oldver }}/examples/ubuntu-lts.yaml
    - name: Install test dependencies
      run: |
        set -eux -o pipefail
        brew install bash coreutils
        brew tap-new lima/qemu
        brew_install_version() {
            FORMULA=$1
            VERSION=$2
            TAP=lima/qemu
            # Extract formula to local tap (this will strip the bottle info)
            EXTRACT=$(brew extract --verbose --force --version "$VERSION" "$FORMULA" "$TAP")
            # Get the commit id for this version
            SHA=$(perl -ne 'print $1 if /from revision ([0-9a-f]+) to/' <<<"$EXTRACT")
            # File path of the extracted formula
            OUTPUT="$(brew --repo "$TAP")/Formula/${FORMULA}@${VERSION}.rb"
            # Get versioned class name of extracted formula
            AT=$(perl -ne 'print $1 if /^class (\w+AT\w+) < Formula/' "$(brew formula "$OUTPUT")")
            # Find the location of the formula inside the homebrew-core, 'Formula/?/$FORMULA'
            FILE=$(brew formula "$FORMULA" | sed 's#^.*/homebrew-core/##')
            REPO=$(brew --repo homebrew/homebrew-core)
            # Overwrite the formula with the original one including bottle info
            git -C "$REPO" show "$SHA:$FILE" >"$OUTPUT"
            # Replace class name with versioned class name
            perl -p -i -e "s/class \w+ < Formula/class $AT < Formula/" "$OUTPUT"
            brew install "${TAP}/qemu@${VERSION}"
        }
        brew_install_version qemu 8.2.1
    - name: Manual install
      run: |
        set -eux -o pipefail
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/v0.23.1/lima-0.23.1-Darwin-x86_64.tar.gz" | tar Cxzvm /usr/local
        env
        qemu-system-x86_64 --version
        limactl --version
        limactl start --tty=false --log-level=debug
        limactl shell default cat /etc/os-release
    - if: always()
      uses: ./.github/actions/upload_failure_logs_if_exists
